name: buildbot
 
on:
  push:
    branches: [ 10.0-wip ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq git curl bc bison flex libssl-dev make libc6-dev libncurses5-dev zip  p7zip-full
        
    - name: Get submodules
      run: git submodule update --init --recursive
      
    - name: Get toolchains
      run: |
        mkdir clang
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-security-10.0.0_r75/clang-r353983c.tar.gz
        tar -C "clang" -xvzf clang-r353983c.tar.gz
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags 
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags
      
    - name: Build
      run: |
        make O=out ARCH=arm64 sirius_defconfig
        PATH="${PWD}/clang/bin:${PWD}/aarch64-linux-android-4.9/bin:${PATH}" \
        make -j4 O=out \
              ARCH=arm64 \
              CLANG_TRIPLE=aarch64-linux-gnu- \
              CROSS_COMPILE=aarch64-linux-android- \
              CC=clang 2>&1 | tee kernel.log    
      env: 
        CROSS_COMPILE_ARM32: $(GITHUB_WORKSPACE)/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
        KBUILD_BUILD_USER: uixdess
 
    - name: Pack
      run: |
        git clone https://github.com/SakuraNotStupid/AnyKernel3
        cp -v out/arch/arm64/boot/Image.gz-dtb AnyKernel3
          pushd AnyKernel3
          7z a -mx9 ../MI8SE-Kernel.zip *
          popd
     
    - name: Uploading Kernel Package to GH-Release
      uses: ncipollo/release-action@v1.8.6
      with:
          artifacts: MI8SE-Kernel.zip
          name: " MI8SE-Kernel"
          tag: " ${{ github.run_number }}_MI8SE-Kernel"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
